# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 23:55
from __future__ import unicode_literals

import apps.videos.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('video_file', models.FileField(upload_to=apps.videos.utils.get_file_path)),
            ],
        ),
    ]
