# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_auto_20151207_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='soundfile_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='soundfile',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
