# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20151209_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albulm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='albulms.Albulm'),
        ),
    ]
