# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('albulms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albulm',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artists.Artist'),
            preserve_default=False,
        ),
    ]
