---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: run apt-get update
      apt: update_cache=yes

    - name: Install required system packages
      apt: name={{ item }} state=installed
      with_items:
        - build-essential
        - libpq-dev
        - python-dev
        - python-setuptools
        - python-pip
        - postgresql-9.3-postgis-2.1
        - postgresql-contrib
        - git 
        - libjpeg-dev
        - fish

    - name: create worker group
      user: name=worker uid=1020

    - name: create cloud user and add to the worker group
      user: name=cloud uid=1010 groups="worker,sudo" password=$6$aPAfjl5w39XCz4qf$Yfjp5AHL1QwdYYiP6omTytTMhAt2YHYJ.yPmr2q5yI7U35fS0FLj2TSWtzL5ps8UiTjyVABkZeNxu5HmxHa33/

    - name: Create cloud root directory and configure permissions
      file: path=/cloud state=directory owner=cloud group=worker  mode="g+s" recurse=yes

    - name: Upgrade pip
      pip: name=pip state=latest

    - name: install virtualenv
      pip: name=virtualenv

    - name: create virtualenv
      command: virtualenv /cloud/sites/cloud/env

    - name: Create data directory
      file: path=/cloud/sites/cloud/data state=directory

    - name: install psycopg2 in order to configure postgres databases
      pip: name=psycopg2

    - name: Create postgres user
      postgresql_user: name=cloud_user password=password
      sudo: yes
      sudo_user: postgres

    - name: Create postgres database
      postgresql_db: name=cloud_db owner=cloud_user
      sudo: yes
      sudo_user: postgres

    - name: Add postgis extension to cloud db
      postgresql_ext: name=postgis db=cloud_db
      sudo: yes
      sudo_user: postgres

    - name: Configure permissions again so they'll apply to the recently created directories
      file: path=/cloud owner=cloud group=worker  mode="g+s" recurse=yes

    # Setup the developer tools
    - name: Create fish config directory
      file: path=~/.config/fish state=directory owner=cloud group=cloud
      sudo_user: cloud

    - name: Install config.fish if it doesn't already exist
      command: cp /cloud/sites/cloud/proj/cloud/developer-tools/config.fish ~/.config/fish/config.fish creates=~/.config/fish/config.fish
      sudo_user: cloud

    - name: Install .vimrc if it doesn't already exist 
      command: cp /cloud/sites/cloud/proj/cloud/developer-tools/.vimrc ~/.vimrc creates=~/.vimrc
      sudo_user: cloud

    - name: Set fish as the default shell 
      user: name=cloud shell=/usr/bin/fish
      sudo: yes     

    # Setup the neccessary production settings
    - name: Install nginx web server
      apt: name=nginx state=installed

    - name: Configure nginx
      copy: src=nginx/production dest=/etc/nginx/sites-available/cloud

    - name: Create neccessary symlink
      file: src=/etc/nginx/sites-available/cloud dest=/etc/nginx/sites-enabled/cloud state=link

    - name: Delete default nginx config file.
      file: path=/etc/nginx/sites-enabled/default state=absent 


    # SETUP NECCESSARY DIRECTORIES
    - name: Create Django static directory
      file: path=/cloud/sites/cloud/ state=directory 

    - name: Create Django static media directory
      file: path=/home/vagrant/www/media state=directory owner=vagrant group=vagrant 

    - name: Create working tree directory
      file: path=/home/vagrant/www/website state=directory


    # SETUP GUNICORN
    - name: Create gunicorn directories
      file: path=/home/vagrant/www/gunicorn state=directory

    - name: Configure gunicorn 
      copy: src=gunicorn/conf.py dest=/cloud/sites/cloud/etc/gunicorn/conf.py


    # SETUP SUPERVISOR
    - name: Install supervisor
      apt: name=supervisor state=installed

    - name: Create supervisor directories
      file: path=/etc/supervisor/conf.d state=directory

    - name: Create supervisor gunicorn log directores
      file: path=/var/log/supervisor/gunicorn state=directory

    - name: setup gunicorn with supervisor
      copy: src=supervisor/gunicorn.conf dest=/etc/supervisor/conf.d/gunicorn.conf

    - name: Install git
      apt: name=git state=installed
