---
- hosts: django_cloud
  user: root
  sudo: yes
  tasks:
    # Clone the repository / pull the latest changes
    - name: clone the repository
      git: repo=https://github.com/giovannicode/django-cloud.git dest=/website/src force=yes

    - name: Configure permissions again so they'll apply to the recently created directories
      file: path=/website owner=website group=worker  mode="g+s" recurse=yes

    - name: Migrate models into database
      django_manage: virtualenv=/website/env/ app_path=/website/src/cloud/ command=migrate
    
    - name: Restart gunicorn
      command: supervisorctl restart gunicorn
